In [1]:
import yfinance as yf
import pandas as pd

In [3]:
msft = yf.Ticker("MSFT")
print(msft.info.get('longName'))
print(msft.info.get('sector'))
print(msft.info.get('industry'))
print(msft.fast_info['lastPrice'])

Microsoft Corporation
Technology
Software - Infrastructure
396.75

In [4]:
tickers_name = pd.read_csv('tickers.csv')
tickers_name

    Ticker
0        A
1       AA
2      ABT
3      ABV
4      ACN
..     ...
500   AKAM
501    TER
502   ENPH
503   FSLR
504   ULTA

[505 rows x 1 columns]

In [10]:
equities = pd.DataFrame(columns=['Ticker', 'Name', 'Sector', 'Industry', 'Last Price'])

In [11]:
for ticker in tickers_name['Ticker']:
    try:
        stock = yf.Ticker(ticker)
        name = stock.info.get('longName')
        sector = stock.info.get('sector')
        industry = stock.info.get('industry')
        last_price = stock.fast_info['lastPrice']
        
        equities = equities.append({
            'Ticker': ticker,
            'Name': name,
            'Sector': sector,
            'Industry': industry,
            'Last Price': last_price
        }, ignore_index=True)
    except Exception as e:
        print(f"Error fetching data for {ticker}: {e}")

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$ABV: possibly delisted; no price data found  (period=1y)
$ABV: possibly delisted; no price data found  (period=5d)
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$BF.B: possibly delisted; no price data found  (period=1y)
$BF.B: possibly delisted; no price data found  (period=5d)
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: BIG"}}}
$BIG: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$BIG: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for BIG: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$BK: possibly delisted; no price data found  (period=1y)
$BK: possibly delisted; no price data found  (period=5d)
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$BRK.A: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$BRK.A: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for BRK.A: 'currentTradingPeriod'

$BRK.B: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$BRK.B: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for BRK.B: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$CDAY: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$CDAY: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for CDAY: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMA"}}}
$CMA: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$CMA: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for CMA: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CTRA"}}}
$CTRA: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$CTRA: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for CTRA: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$DFS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$DFS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for DFS: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$FLT: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$FLT: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for FLT: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GES"}}}
$GES: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$GES: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for GES: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HES"}}}
$HES: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$HES: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for HES: 'currentTradingPeriod'

$HFC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$HFC: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for HFC: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IPG"}}}
$IPG: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$IPG: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for IPG: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JNPR"}}}
$JNPR: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$JNPR: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for JNPR: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: JWN"}}}
$JWN: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$JWN: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for JWN: 'currentTradingPeriod'

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: K"}}}
$K: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$K: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for K: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$KSU: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$KSU: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for KSU: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$MMC: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$MMC: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for MMC: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$MRO: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$MRO: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for MRO: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$NYCB: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$NYCB: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for NYCB: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$PEK: possibly delisted; no price data found  (period=1y)
$PEK: possibly delisted; no price data found  (period=5d)
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: PX"}}}
$PX: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$PX: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for PX: 'currentTradingPeriod'

$PXD: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$PXD: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for PXD: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$RE: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$RE: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for RE: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TGNA"}}}
$TGNA: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$TGNA: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for TGNA: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$TTW: possibly delisted; no price data found  (period=1y)
$TTW: possibly delisted; no price data found  (period=5d)
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$VAR: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$VAR: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for VAR: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}
$WBA: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$WBA: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for WBA: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$WRK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$WRK: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for WRK: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: X"}}}
$X: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$X: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for X: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({

Error fetching data for CMA: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}
$WBA: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$WBA: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for WBA: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
$SPLK: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
$SPLK: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Error fetching data for SPLK: 'currentTradingPeriod'

C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({
C:\Users\Radek\AppData\Local\Temp\ipykernel_25528\2528024103.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  equities = equities.append({

In [12]:
equities

,Ticker,Name,Sector,Industry,Last Price
0,A,"Agilent Technologies, Inc.",Healthcare,Diagnostics & Research,136.029999
1,AA,Alcoa Corporation,Basic Materials,Aluminum,47.645
2,ABT,Abbott Laboratories,Healthcare,Medical Devices,89.790001
3,ABV,None,None,None,None
4,ACN,Accenture plc,Technology,Information Technology Services,138.684998
...,...,...,...,...,...
470,AKAM,"Akamai Technologies, Inc.",Technology,Software - Infrastructure,120.260002
471,TER,"Teradyne, Inc.",Technology,Semiconductor Equipment & Materials,338.590302
472,ENPH,"Enphase Energy, Inc.",Technology,Solar,43.830002
473,FSLR,"First Solar, Inc.",Technology,Solar,223.279999
474,ULTA,"Ulta Beauty, Inc.",Consumer Cyclical,Specialty Retail,472.519989

In [13]:
equities = equities.dropna(how='any').reset_index(drop=True)
equities

,Ticker,Name,Sector,Industry,Last Price
0,A,"Agilent Technologies, Inc.",Healthcare,Diagnostics & Research,136.029999
1,AA,Alcoa Corporation,Basic Materials,Aluminum,47.645
2,ABT,Abbott Laboratories,Healthcare,Medical Devices,89.790001
3,ACN,Accenture plc,Technology,Information Technology Services,138.684998
4,AEM,Agnico Eagle Mines Limited,Basic Materials,Gold,141.154999
...,...,...,...,...,...
466,AKAM,"Akamai Technologies, Inc.",Technology,Software - Infrastructure,120.260002
467,TER,"Teradyne, Inc.",Technology,Semiconductor Equipment & Materials,338.590302
468,ENPH,"Enphase Energy, Inc.",Technology,Solar,43.830002
469,FSLR,"First Solar, Inc.",Technology,Solar,223.279999
470,ULTA,"Ulta Beauty, Inc.",Consumer Cyclical,Specialty Retail,472.519989